<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: ym
 * Date: Thu, 01 Mar 2018 01:49:10 +0100
 */

$conf['title'] = 'Social Engineering';
$conf['sidebar'] = '';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
